CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  section TEXT NOT NULL,
  title TEXT NOT NULL,
  date TEXT,
  when_text TEXT,
  where_text TEXT,
  img TEXT,
  body TEXT NOT NULL DEFAULT '[]',
  links TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('featured','The Stranger & Beethoven’s Tango','2026-09-11','Friday, September 11th','Lobero Theatre','/events/tango.jpg','["Catch a few of our featured aerialists in Meredith Ventura\u2019s newest work, The Stranger. Performed alongside Fernanda Ghi and Alfredo Minetti\u2019s brand-new work Beethoven\u2019s Tango, this evening brings together two works concerned with the artist\u2019s inner world and the forces that shape expression.", "Beethoven\u2019s Tango merges dance and live music into a singular theatrical experience.", "Together, The Stranger and Beethoven\u2019s Tango ask what it means to create, to be seen, and to remain human in a world that often misunderstands the depths of feeling."]','[{"label": "Get Tickets", "url": "https://selah.dance/"}]',0);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('featured','Santa Barbara Pride Festival','2026-08-22','Saturday, Aug 22nd · 12–6pm','Chase Palm Park','/events/pride.jpeg','["Wrap up the summer sharing what we love and celebrating love! We have been invited back to perform beachside at Pacific Pride Foundation''s Pride Festival happening at Chase Palm Park!", "An epic day of DJs, live music, drag shows, vendors, playing & dancing right next to the beach, celebrating love in all its many forms! Sign up or just come hang with us \u2014 the rig will be up noon to 6pm."]','[{"label": "Pacific Pride Foundation", "url": "https://pacificpridefoundation.org/summer-of-pride/pacific-pride-festival/"}]',1);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('featured','In-House Showcase & Jam','2026-07-31','Friday, July 31st · 6–8pm','Elemental Arts Studio','/events/showcase.png','["Join us for an in-house studio showcase celebrating progress, creativity, and community! Jam out with the EA crew!", "6\u20137pm \u2014 Open Hang / Jam Time: bounce ideas with your friends, show a friend a new apparatus, come hang. We will have all sorts of apparatuses up. Newcomers welcome!", "7\u20138pm \u2014 In-House Studio Showcase: feeling called to share what you love? Here''s a chance to do just that in a relaxed and supportive environment. Share a polished piece, freestyle, or simply cheer others on. Works in progress, silly, or serious \u2014 all are welcome in this safe space to test ideas! Your act does NOT need to be aerial: dance, flow, and \"circus other\" welcomed!"]',NULL,2);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('featured','Elemental Bloom — Spring Showcase ft. Pyrokitten Conclave','2025-05-29','Thursday, May 29th · Doors 7pm, Show 7:30–9pm','Buena Onda SB','/events/bloom.jpg','["A night of yummy aerial art and epic fire performances! Aerialists from Elemental Arts have been deep in the sauce, creating brand-new solo acts that have been blooming in their hearts, and they can''t wait to share with you all. Pyrokitten Fire Conclave will be performing sick group fire acts they have been creating all spring.", "This is a donation-based show. Bring a friend and step into the romantic outdoor atmosphere of Buena Onda, where the enchanting Argentine ambiance awaits \u2014 food and drinks available from Buena Onda''s kitchen all evening long!"]','[{"label": "Buena Onda SB", "url": "https://www.buenaondasb.com/"}, {"label": "@pyrokittenconclave", "url": "https://www.instagram.com/pyrokittenconclave/"}]',3);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('featured','Wildflowers: A Story Told Through Aerial, Circus, and Dance','2024-06-01','Past Production',NULL,'/events/wildflowers.jpeg','["With a special prequel by Paper Doll Militia & Circus with a Purpose. How do art & movement help us to heal? Seen through the lens of aerial, circus, and dance arts, our artists navigate the body''s natural survival responses: fight, flight, freeze and fawn.", "In the summertime, we dance through lush fields. But in the dry fall heat, a wildfire engulfs the vibrant landscape, leaving scorched earth in its wake. In the harsh grip of winter, we roam through fields of withering wildflowers, each flower representing our bodies'' natural responses to this communal trauma. But why do these emotions seem so negative? Have they come as guides to teach us something about ourselves?"]','[{"label": "Watch the Full Show on YouTube", "url": "https://www.youtube.com/watch?v=Mqpc9g0E7BQ"}, {"label": "Show Photos", "url": "https://www.facebook.com/media/set/?set=a.10236981861106212&type=3"}]',4);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('show','Santa Barbara Earth Day','2026-04-25','April 25th, 2026',NULL,NULL,'["Find our aerialists flying high in Alameda Park for Santa Barbara''s Earth Day Festival!"]','[{"label": "Learn More", "url": "https://www.sbearthday.org/"}]',0);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('show','Santa Barbara Summer Solstice Festival','2026-06-20','June 20th, 2026',NULL,NULL,'["Find our flyers performing alongside the music at the mainstage in Alameda Park!"]','[{"label": "Learn More", "url": "https://www.solsticeparade.com/"}]',1);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('show','Pacific Pride at the Beach Festival','2025-08-23','August 23rd, 2025',NULL,NULL,'["Hang with us at Cabrillo Beach Park 11am\u20137pm. A free event celebrating the beauty, art, and creativity LGBTQ+ individuals bring to the world."]','[{"label": "Learn More", "url": "https://pacificpridefoundation.org/summer-of-pride/pacific-pride-festival/"}]',2);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('show','Boo at the Zoo','2025-10-31','October 2025',NULL,NULL,'["Every night 5\u20138pm at the Santa Barbara Zoo''s \"spell-a-bration\"! Six nights of Halloween spirit, trick-or-treating for kids, tasty treats and boo-zy adult beverages."]','[{"label": "Learn More", "url": "https://www.sbzoo.org/boo-at-the-zoo/"}]',3);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('retreat','Popoyo, Nicaragua — Aerial, Circus & Yoga Retreat',NULL,'All month long · weekly options available',NULL,'/events/retreat_nicaragua.jpeg','["Acro, Aerial, Yoga Impact Retreat with Circus with Purpose. Connect with purpose through yoga and circus. Step into a breathtakingly beautiful setting and co-create with a dynamic family of passionate instructors, artists and fellow retreaters.", "Immerse yourself in new moves, ideas, friends and food. Expertly curated to inspire creativity, movement mastery and lifelong, cross-cultural connections in Nicaragua. Donate and build circus community for local schools!"]','[{"label": "circuswithpurpose.art", "url": "https://www.circuswithpurpose.art/"}]',0);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('retreat','Fire and Flight Retreat — Twentynine Palms',NULL,'3 days in the desert',NULL,'/events/retreat_fire.jpg','["Join us in the Twentynine Palms desert for 3 days of creative expression through aerial and fire dance. Hosted by Cirque du Soleil artist Amanda Ritchie and award-winning fire dancer Cat LaCohie."]','[{"label": "Retreat Details", "url": "https://www.vixendeville.com/retreat/"}]',1);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('fave','Santa Barbara Earth Day',NULL,'April',NULL,NULL,'[]',NULL,0);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('fave','Shabang Music Festival',NULL,'May',NULL,NULL,'[]',NULL,1);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('fave','Santa Barbara Summer Solstice Festival',NULL,'June',NULL,NULL,'[]',NULL,2);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('fave','Pacific Pride at the Beach Festival',NULL,'August',NULL,NULL,'[]',NULL,3);
INSERT INTO posts (section,title,date,when_text,where_text,img,body,links,sort_order) VALUES ('fave','Boo at the Zoo',NULL,'October',NULL,NULL,'[]',NULL,4);
